=begin
#Adzerk Decision API

#Adzerk Decision API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

module AdzerkDecisionSdk
  VERSION = '1.0.0-beta.12'
end
