# -*- encoding: utf-8 -*-

=begin
#Adzerk Decision API

#Adzerk Decision API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "adzerk_decision_sdk/version"

Gem::Specification.new do |s|
  s.name        = "adzerk_decision_sdk"
  s.version     = AdzerkDecisionSdk::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Adzerk, Inc."]
  s.email       = ["engineering@adzerk.com"]
  s.homepage    = "http://adzerk.com"
  s.summary     = "Adzerk Decision API"
  s.description = "Ruby library for the Adzerk Decision API"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
