=begin
#Adzerk Decision API

#Adzerk Decision API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Adzerk::Decision::Generated::DecisionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DecisionApi' do
  before do
    # run before each test
    @api_instance = Adzerk::Decision::Generated::DecisionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DecisionApi' do
    it 'should create an instance of DecisionApi' do
      expect(@api_instance).to be_instance_of(Adzerk::Decision::Generated::DecisionApi)
    end
  end

  # unit tests for get_decisions
  # Request Decision(s)
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [Response]
  describe 'get_decisions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
