=begin
#Adzerk Decision API

#Adzerk Decision API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'date'

module AdzerkDecisionSdk
  class Request
    # One or more Placement objects
    attr_accessor :placements

    attr_accessor :user

    # Keywords for keyword Targeting. Such as `\"keywords\": [\"foo\", \"bar\", \"baz\"]`.
    attr_accessor :keywords

    # The current page URL
    attr_accessor :url

    # The referrer URL
    attr_accessor :referrer

    # The IP address. Required for [Geo-Targeting](https://dev.adzerk.com/docs/geo-location)
    attr_accessor :ip

    # Numeric creative ids to disregard for ad selection
    attr_accessor :blocked_creatives

    # If true, only ads containing a single image will be returned
    attr_accessor :is_mobile

    # If true, return pricing data for the decision in the response
    attr_accessor :include_pricing_data

    # If true, only return ads that are set to honor Do Not Track
    attr_accessor :notrack

    # If making a client-side request, set to true. Defaults to false to ensure a server isn't seen as a bot. See [here](https://dev.adzerk.com/docs/tracking-overview#section-bot-filtering) for more info
    attr_accessor :enable_bot_filtering

    # If true, override the IP address of the request with the IP address supplied on the UserKey. If no IP address is found on the UserKey, this will fall back to the IP address on the request. Requires UserDB
    attr_accessor :enable_user_dbip

    attr_accessor :consent

    # RTB requests only - sets an Identifier for Advertisers (IFA or IDFA)
    attr_accessor :device_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'placements' => :'placements',
        :'user' => :'user',
        :'keywords' => :'keywords',
        :'url' => :'url',
        :'referrer' => :'referrer',
        :'ip' => :'ip',
        :'blocked_creatives' => :'blockedCreatives',
        :'is_mobile' => :'isMobile',
        :'include_pricing_data' => :'includePricingData',
        :'notrack' => :'notrack',
        :'enable_bot_filtering' => :'enableBotFiltering',
        :'enable_user_dbip' => :'enableUserDBIP',
        :'consent' => :'consent',
        :'device_id' => :'deviceID'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'placements' => :'Array<Placement>',
        :'user' => :'User',
        :'keywords' => :'Array<String>',
        :'url' => :'String',
        :'referrer' => :'String',
        :'ip' => :'String',
        :'blocked_creatives' => :'Array<Integer>',
        :'is_mobile' => :'Boolean',
        :'include_pricing_data' => :'Boolean',
        :'notrack' => :'Boolean',
        :'enable_bot_filtering' => :'Boolean',
        :'enable_user_dbip' => :'Boolean',
        :'consent' => :'RequestConsent',
        :'device_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'keywords',
        :'url',
        :'referrer',
        :'ip',
        :'blocked_creatives',
        :'is_mobile',
        :'include_pricing_data',
        :'notrack',
        :'enable_bot_filtering',
        :'enable_user_dbip',
        :'consent',
        :'device_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AdzerkDecisionSdk::Request` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AdzerkDecisionSdk::Request`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'placements')
        if (value = attributes[:'placements']).is_a?(Array)
          self.placements = value
        end
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'keywords')
        if (value = attributes[:'keywords']).is_a?(Array)
          self.keywords = value
        end
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'referrer')
        self.referrer = attributes[:'referrer']
      end

      if attributes.key?(:'ip')
        self.ip = attributes[:'ip']
      end

      if attributes.key?(:'blocked_creatives')
        if (value = attributes[:'blocked_creatives']).is_a?(Array)
          self.blocked_creatives = value
        end
      end

      if attributes.key?(:'is_mobile')
        self.is_mobile = attributes[:'is_mobile']
      end

      if attributes.key?(:'include_pricing_data')
        self.include_pricing_data = attributes[:'include_pricing_data']
      end

      if attributes.key?(:'notrack')
        self.notrack = attributes[:'notrack']
      end

      if attributes.key?(:'enable_bot_filtering')
        self.enable_bot_filtering = attributes[:'enable_bot_filtering']
      end

      if attributes.key?(:'enable_user_dbip')
        self.enable_user_dbip = attributes[:'enable_user_dbip']
      end

      if attributes.key?(:'consent')
        self.consent = attributes[:'consent']
      end

      if attributes.key?(:'device_id')
        self.device_id = attributes[:'device_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @placements.nil?
        invalid_properties.push('invalid value for "placements", placements cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @placements.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          placements == o.placements &&
          user == o.user &&
          keywords == o.keywords &&
          url == o.url &&
          referrer == o.referrer &&
          ip == o.ip &&
          blocked_creatives == o.blocked_creatives &&
          is_mobile == o.is_mobile &&
          include_pricing_data == o.include_pricing_data &&
          notrack == o.notrack &&
          enable_bot_filtering == o.enable_bot_filtering &&
          enable_user_dbip == o.enable_user_dbip &&
          consent == o.consent &&
          device_id == o.device_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [placements, user, keywords, url, referrer, ip, blocked_creatives, is_mobile, include_pricing_data, notrack, enable_bot_filtering, enable_user_dbip, consent, device_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AdzerkDecisionSdk.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
